set(EXTENSIONS_DIR ${CMAKE_CURRENT_LIST_DIR}/superbuild-extensions)
# include(${EXTENSIONS_DIR}/gui/mc_rtc-magnum.cmake)

# set(DRCUTIL_DIR ${CMAKE_CURRENT_LIST_DIR}/drcutil-superbuild)
# include(${DRCUTIL_DIR}/full.cmake)
# include(${DRCUTIL_DIR}/openrtm2.cmake)
# include(${DRCUTIL_DIR}/drcutil.cmake)
# include(${DRCUTIL_DIR}/choreonoid.cmake)
# include(${DRCUTIL_DIR}/mc-openrtm.cmake)

include(${CMAKE_CURRENT_LIST_DIR}/interfaces/mc_mujoco.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/panda_mj_description.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/rhps1_mj_description.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/hrp5_mj_description.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/kinova_mj_description.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_imu_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_force_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_energy_residual.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_energy_residual_current.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_energy_residual_torque.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_current_residual.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_torque_residual.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_zurlo.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_momentum_error.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_pi_sliding.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_force_torque_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_jerk.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_super_twisting.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_adc_collision_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_residual_estimation.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_passivity_torque_feedback.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/ral_exp_external_forces.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/minimum_jerk_task.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/circular_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_joystick_plugin.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/monodzukuri2024_kinova_demo.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/fitts_law_controller.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_force_sensor_calibration_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/obstacle_detection_jerk_estimator.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/figaroh_identification_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/ijrr_vel_drop_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_monitoring_birjandi.cmake)




include(${CMAKE_CURRENT_LIST_DIR}/controllers/collision_benchmark_controller.cmake)

include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_posture_pub_sub.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/posture_datastore_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/mc_svlr.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/interfaces/mc_h1.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/baseline_walking_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/lipm_walking_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/planning/ismpc-walking-superbuild.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/torque_test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/rl_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/force_rl_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/kinova_gravity_compensation_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/kinova_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/fsm_torque_pd_task_tester.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/pid_tuning_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/rl_kinova_ball_balancing_mc_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/new-rl-qp-controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/hrp5p_rl_qp_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/sandbox_humanoid_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/observers/mc_external_forces_observer.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/robots/rhp7.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/rhp7_mj_description.cmake)
